# Taps
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'stripe/stripe-cli'

# Binaries
brew 'bash'
brew 'coreutils'
brew 'curl'
brew 'gh'
brew 'git'
brew 'grep'
brew 'mackup'
brew 'svn' # Needed to install fonts

# Development
brew 'fnm'
brew 'stripe/stripe-cli/stripe'

# Apps
cask '1password'
cask 'dbngin'
cask 'docker'
cask 'expressvpn'
cask 'firefox'
cask 'github'
cask 'google-chrome'
cask 'herd'
cask 'insomnia'
cask 'iterm2'
cask 'lando'
cask 'phpstorm'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'tableplus'
cask 'visual-studio-code'
cask 'zoom'

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
